# TCL File Generated by Component Editor 15.1
# Tue Aug 16 21:21:26 CST 2016
# DO NOT MODIFY


# 
# avalon_mm_master "avalon_mm_master" v1.0
#  2016.08.16.21:21:26
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module avalon_mm_master
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_mm_master
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon_mm_master
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_master_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_master_interface.v VERILOG PATH avalon_master_interface.v TOP_LEVEL_FILE
add_fileset_file FlipFlopD_Habilitado.v VERILOG PATH ../FlipFlopD_Habilitado.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avalon_master_interface
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_master_interface.v VERILOG PATH avalon_master_interface.v
add_fileset_file FlipFlopD_Habilitado.v VERILOG PATH ../FlipFlopD_Habilitado.v


# 
# parameters
# 
add_parameter DATA_BITS INTEGER 8
set_parameter_property DATA_BITS DEFAULT_VALUE 8
set_parameter_property DATA_BITS DISPLAY_NAME DATA_BITS
set_parameter_property DATA_BITS TYPE INTEGER
set_parameter_property DATA_BITS UNITS None
set_parameter_property DATA_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_BITS HDL_PARAMETER true
add_parameter ADDRESS_BITS INTEGER 5
set_parameter_property ADDRESS_BITS DEFAULT_VALUE 5
set_parameter_property ADDRESS_BITS DISPLAY_NAME ADDRESS_BITS
set_parameter_property ADDRESS_BITS TYPE INTEGER
set_parameter_property ADDRESS_BITS UNITS None
set_parameter_property ADDRESS_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDRESS_BITS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master avalon_wait_request waitrequest Input 1
add_interface_port avalon_master avalon_address address Output ADDRESS_BITS
add_interface_port avalon_master avalon_read read Output 1
add_interface_port avalon_master avalon_write write Output 1
add_interface_port avalon_master avalon_write_data writedata Output DATA_BITS
add_interface_port avalon_master avalon_read_data readdata Input DATA_BITS


# 
# connection point control
# 
add_interface control conduit end
set_interface_property control associatedClock clock
set_interface_property control associatedReset reset
set_interface_property control ENABLED true
set_interface_property control EXPORT_OF ""
set_interface_property control PORT_NAME_MAP ""
set_interface_property control CMSIS_SVD_VARIABLES ""
set_interface_property control SVD_ADDRESS_GROUP ""

add_interface_port control datos_escribir datos_escribir Input DATA_BITS
add_interface_port control direccion direccion Input ADDRESS_BITS
add_interface_port control escribir escribir Input 1
add_interface_port control leer leer Input 1
add_interface_port control transaccion_completada transaccion_completada Output 1
add_interface_port control datos_leidos datos_leidos Output DATA_BITS

