// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 15.1 (Build Build 185 10/21/2015)
// Created on Sat Aug 20 19:03:12 2016

control_mascara control_mascara_inst
(
	.clk(),
	.reset(),
	.direccion_registros(),
	.datos_registros(),
	.habilitacion_registros(),
	.direccion_mem()
);

defparam control_mascara_inst.BITS_BUS_DATOS = 21;
defparam control_mascara_inst.BITS_BUS_DIRECCION = 11;
defparam control_mascara_inst.BITS_DIRECCION_MEM = 10;
