// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 15.1 (Build Build 185 10/21/2015)
// Created on Sat Sep 10 14:42:43 2016

control_lecturas_mem_externa control_lecturas_mem_externa_inst
(
	.clk(clk_sig),
	.reset(reset_sig),
	.iniciar(iniciar_sig),
	.buf_space_available(buf_space_available_sig),
	.direccion_mem_inicio_img(direccion_mem_inicio_img_sig),
	.lecturas_totales_mem(lecturas_totales_mem_sig),
	.lectura_mem_completada(lectura_mem_completada_sig),
	.read_mem(read_mem_sig),
	.address_mem(address_mem_sig),
	.save_mem_data(save_mem_data_sig)
);

defparam control_lecturas_mem_externa_inst.BITS_BUS_DATOS_INSTR = 21;
