// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 15.1 (Build Build 185 10/21/2015)
// Created on Fri Sep 16 09:46:08 2016

convolucion_mascara_ventana convolucion_mascara_ventana_inst
(
	.clk(clk),
	.reset(reset),
	.ventana_pixeles_lista(ventana_pixeles_lista),
	.denominador(denominador),
	.tamano_mascara(tamano_mascara),
	.mask_value_1(mask_value_1),
	.mask_value_2(mask_value_2),
	.mask_value_3(mask_value_3),
	.mask_value_4(mask_value_4),
	.mask_value_5(mask_value_5),
	.mask_value_6(mask_value_6),
	.mask_value_7(mask_value_7),
	.mask_value_8(mask_value_8),
	.mask_value_9(mask_value_9),
	.mask_value_10(mask_value_10),
	.mask_value_11(mask_value_11),
	.mask_value_12(mask_value_12),
	.mask_value_13(mask_value_13),
	.mask_value_14(mask_value_14),
	.mask_value_15(mask_value_15),
	.mask_value_16(mask_value_16),
	.mask_value_17(mask_value_17),
	.mask_value_18(mask_value_18),
	.mask_value_19(mask_value_19),
	.mask_value_20(mask_value_20),
	.mask_value_21(mask_value_21),
	.mask_value_22(mask_value_22),
	.mask_value_23(mask_value_23),
	.mask_value_24(mask_value_24),
	.mask_value_25(mask_value_25),
	.pixel_value_1(pixel_value_1),
	.pixel_value_2(pixel_value_2),
	.pixel_value_3(pixel_value_3),
	.pixel_value_4(pixel_value_4),
	.pixel_value_5(pixel_value_5),
	.pixel_value_6(pixel_value_6),
	.pixel_value_7(pixel_value_7),
	.pixel_value_8(pixel_value_8),
	.pixel_value_9(pixel_value_9),
	.pixel_value_10(pixel_value_10),
	.pixel_value_11(pixel_value_11),
	.pixel_value_12(pixel_value_12),
	.pixel_value_13(pixel_value_13),
	.pixel_value_14(pixel_value_14),
	.pixel_value_15(pixel_value_15),
	.pixel_value_16(pixel_value_16),
	.pixel_value_17(pixel_value_17),
	.pixel_value_18(pixel_value_18),
	.pixel_value_19(pixel_value_19),
	.pixel_value_20(pixel_value_20),
	.pixel_value_21(pixel_value_21),
	.pixel_value_22(pixel_value_22),
	.pixel_value_23(pixel_value_23),
	.pixel_value_24(pixel_value_24),
	.pixel_value_25(pixel_value_25),
	.pixel_resultado(pixel_resultado),
	.pixel_calculado(pixel_calculado)
);

defparam convolucion_mascara_ventana_inst.BITS_ELEMENTO_MASCARA = 10;
defparam convolucion_mascara_ventana_inst.BITS_PIXEL = 8;
defparam convolucion_mascara_ventana_inst.BITS_PRODUCTO_SUMA = 11;
defparam convolucion_mascara_ventana_inst.BITS_MASCARA = 3;
