// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 15.1 (Build Build 185 10/21/2015)
// Created on Thu Aug 18 21:57:53 2016

FSM_prueba_escritura_mem FSM_prueba_escritura_mem_inst
(
	.clk(),
	.reset(),
	.iniciar_prueba(),
	.operacion_completada(),
	.datos_leidos(),
	.leer(),
	.escribir(),
	.datos_por_escribir(),
	.direccion_memoria()
);

defparam FSM_prueba_escritura_mem_inst.ADDRESS_BITS = 18;
defparam FSM_prueba_escritura_mem_inst.DATA_BITS = 64;
