// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 15.1 (Build Build 185 10/21/2015)
// Created on Mon Aug 22 18:49:41 2016

mascara_filtro mascara_filtro_inst
(
	.clk(),
	.reset(),
	.tamano_mascara(),
	.direccion_mem_inicio_mascara(),
	.iniciar_lectura(),
	.lectura_completada(),
	.datos_memoria(),
	.direccion_mem_fisica(),
	.leer(),
	.mascara_valida(),
	.valor_mascara_1(),
	.valor_mascara_2(),
	.valor_mascara_3(),
	.valor_mascara_4(),
	.valor_mascara_5(),
	.valor_mascara_6(),
	.valor_mascara_7(),
	.valor_mascara_8(),
	.valor_mascara_9(),
	.valor_mascara_10(),
	.valor_mascara_11(),
	.valor_mascara_12(),
	.valor_mascara_13(),
	.valor_mascara_14(),
	.valor_mascara_15(),
	.valor_mascara_16(),
	.valor_mascara_17(),
	.valor_mascara_18(),
	.valor_mascara_19(),
	.valor_mascara_21(),
	.valor_mascara_22(),
	.valor_mascara_23(),
	.valor_mascara_24(),
	.valor_mascara_25(),
	.valor_mascara_26(),
	.valor_mascara_27()
);

defparam mascara_filtro_inst.BITS_MASCARA = 3;
defparam mascara_filtro_inst.BITS_DIRECCION_MEM = 10;
