# TCL File Generated by Component Editor 15.1
# Fri Aug 19 09:03:41 CST 2016
# DO NOT MODIFY


# 
# master_prueba_mem "master_prueba_mem" v1.0
#  2016.08.19.09:03:41
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module master_prueba_mem
# 
set_module_property DESCRIPTION ""
set_module_property NAME master_prueba_mem
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME master_prueba_mem
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL FSM_prueba_escritura_mem
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file FSM_prueba_escritura_mem.v VERILOG PATH source_code/FSM_prueba_escritura_mem.v TOP_LEVEL_FILE
add_fileset_file FlipFlopD_Habilitado.v VERILOG PATH source_code/FlipFlopD_Habilitado.v
add_fileset_file registro_sumador.v VERILOG PATH source_code/registro_sumador.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL FSM_prueba_escritura_mem
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file FSM_prueba_escritura_mem.v VERILOG PATH source_code/FSM_prueba_escritura_mem.v
add_fileset_file FlipFlopD_Habilitado.v VERILOG PATH source_code/FlipFlopD_Habilitado.v
add_fileset_file registro_sumador.v VERILOG PATH source_code/registro_sumador.v


# 
# parameters
# 
add_parameter ADDRESS_BITS INTEGER 18
set_parameter_property ADDRESS_BITS DEFAULT_VALUE 18
set_parameter_property ADDRESS_BITS DISPLAY_NAME ADDRESS_BITS
set_parameter_property ADDRESS_BITS TYPE INTEGER
set_parameter_property ADDRESS_BITS UNITS None
set_parameter_property ADDRESS_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDRESS_BITS HDL_PARAMETER true
add_parameter DATA_BITS INTEGER 64
set_parameter_property DATA_BITS DEFAULT_VALUE 64
set_parameter_property DATA_BITS DISPLAY_NAME DATA_BITS
set_parameter_property DATA_BITS TYPE INTEGER
set_parameter_property DATA_BITS UNITS None
set_parameter_property DATA_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_BITS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point control_master
# 
add_interface control_master conduit end
set_interface_property control_master associatedClock clock
set_interface_property control_master associatedReset reset
set_interface_property control_master ENABLED true
set_interface_property control_master EXPORT_OF ""
set_interface_property control_master PORT_NAME_MAP ""
set_interface_property control_master CMSIS_SVD_VARIABLES ""
set_interface_property control_master SVD_ADDRESS_GROUP ""

add_interface_port control_master operacion_completada transaccion_completada Input 1
add_interface_port control_master datos_leidos datos_leidos Input DATA_BITS
add_interface_port control_master leer leer Output 1
add_interface_port control_master escribir escribir Output 1
add_interface_port control_master datos_por_escribir datos_escribir Output DATA_BITS
add_interface_port control_master direccion_memoria direccion Output ADDRESS_BITS


# 
# connection point control_externo
# 
add_interface control_externo conduit end
set_interface_property control_externo associatedClock clock
set_interface_property control_externo associatedReset reset
set_interface_property control_externo ENABLED true
set_interface_property control_externo EXPORT_OF ""
set_interface_property control_externo PORT_NAME_MAP ""
set_interface_property control_externo CMSIS_SVD_VARIABLES ""
set_interface_property control_externo SVD_ADDRESS_GROUP ""

add_interface_port control_externo iniciar_prueba iniciar_prueba Input 1

