// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 15.1 (Build Build 185 10/21/2015)
// Created on Tue Sep 27 19:46:31 2016

program_counter program_counter_inst
(
	.clk(),
	.reset(),
	.iniciar(),
	.reiniciar(),
	.lectura_completada(),
	.instruccion_actual(),
	.leer_siguiente_inst(),
	.direccion_siguiente_inst()
);

defparam program_counter_inst.TAMANO_INSTRUCCION = 32;
defparam program_counter_inst.BITS_DIRECCION_MEMORIA = 14;
