// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 15.1 (Build Build 185 10/21/2015)
// Created on Sat Sep 17 21:40:42 2016

ventana_pixeles ventana_pixeles_inst
(
	.clk(),
	.reset(),
	.cantidad_buffers_internos(),
	.tamano_mascara(),
	.data_available(),
	.iniciar(),
	.pixel_entrada(),
	.read_pixel(),
	.pixel_1(),
	.pixel_2(),
	.pixel_3(),
	.pixel_4(),
	.pixel_5(),
	.pixel_6(),
	.pixel_7(),
	.pixel_8(),
	.pixel_9(),
	.pixel_10(),
	.pixel_11(),
	.pixel_12(),
	.pixel_13(),
	.pixel_14(),
	.pixel_15(),
	.pixel_16(),
	.pixel_17(),
	.pixel_18(),
	.pixel_19(),
	.pixel_20(),
	.pixel_21(),
	.pixel_22(),
	.pixel_23(),
	.pixel_24(),
	.pixel_25()
);

defparam ventana_pixeles_inst.BITS_PIXEL = 8;
defparam ventana_pixeles_inst.BITS_BUFFERS = 3;
defparam ventana_pixeles_inst.BITS_MASCARA = 3;
